# Generated by Django 4.2.6 on 2024-02-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('subject', models.CharField(choices=[('D', 'Data Gathering'), ('O', 'Online Evaluation')], max_length=2)),
                ('secret', models.CharField(default='11bd19f0a8ddb3126c7a5af635ac3dd6', max_length=16)),
                ('granted', models.BooleanField(default=False)),
            ],
        ),
    ]
