# Generated by Django 4.2.6 on 2024-02-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='secret',
            field=models.CharField(default='382f734948affba86f0fd8dc7c132c53f1f565a0df6b6e224b1f586fc575354c', max_length=32),
        ),
    ]
