# Generated by Django 4.2.6 on 2024-02-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0002_alter_token_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='secret',
            field=models.CharField(default='ff2128fdf38909ad589370f4a80a3cf6', max_length=32),
        ),
    ]
