# Generated by Django 4.2.6 on 2024-02-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0003_alter_token_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='secret',
            field=models.CharField(default='3eebc2fb3c764333', max_length=16),
        ),
    ]
