# Generated by Django 4.2.6 on 2024-02-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0007_alter_token_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='granted',
        ),
        migrations.AddField(
            model_name='token',
            name='status',
            field=models.CharField(choices=[('Permissioned', 'Permissioned'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='token',
            name='subject',
            field=models.CharField(choices=[('Data Gathering', 'Data Gathering'), ('Online Evaluation', 'Online Evaluation')], max_length=20),
        ),
    ]
