# Generated by Django 4.2.6 on 2024-01-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='cpanel/profile/avatar/default_avatar.png', upload_to='profile/avatar/'),
        ),
    ]
