# Generated by Django 4.2.6 on 2024-01-15 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mindnet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, default=None)),
                ('framework', models.CharField(choices=[('Scikit-learn', 'Scikit-learn'), ('Keras', 'Keras'), ('Pytorch', 'Pytorch')], default='Scikit-learn', max_length=15)),
                ('approach', models.CharField(choices=[('DL', 'Deep Learning'), ('ML', 'Machine Learning')], default='ML', max_length=20)),
                ('model', models.FileField(blank=True, default=None, upload_to='Ai_models/')),
                ('model_code', models.TextField(blank=True, null=True)),
                ('private', models.BooleanField(default=False)),
                ('related_dataset', models.ManyToManyField(blank=True, to='mindnet.dataset')),
                ('related_paper', models.ManyToManyField(blank=True, to='mindnet.paper')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_aimodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
