# Generated by Django 4.2.6 on 2024-01-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindnet', '0002_aimodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='hyperparameters',
            field=models.TextField(blank=True, null=True),
        ),
    ]
