# Generated by Django 4.2.6 on 2024-01-15 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mindnet', '0003_aimodel_hyperparameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preprocess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, default=None)),
                ('preprocess_code', models.TextField(blank=True, null=True)),
                ('hyperparameters', models.TextField(blank=True, null=True)),
                ('private', models.BooleanField(default=False)),
                ('related_paper', models.ManyToManyField(blank=True, to='mindnet.paper')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_preprocess', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
