# Generated by Django 4.2.6 on 2024-01-15 12:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mindnet', '0005_crossvalidation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_type', models.CharField(choices=[('Subject Independent', 'SI'), ('Subject Dependent', 'SD')], default='standard_1020', max_length=20)),
                ('test_size', models.FloatField(default=0.3, max_length=5)),
                ('tmin', models.FloatField(default=0.5, max_length=5)),
                ('tmax', models.FloatField(default=2.5, max_length=5)),
                ('event_id', models.CharField(default='10,11', max_length=30)),
                ('montage', models.BooleanField(default=False)),
                ('montage_type', models.CharField(choices=[(False, 'None'), ('standard_1005', 'standard_1005'), ('standard_1020', 'standard_1020')], default='standard_1020', max_length=20)),
                ('filter', models.CharField(choices=[(False, 'None'), ('Bandpass', 'Bandpass')], default='Bandpass', max_length=20)),
                ('low_band', models.FloatField(default=100)),
                ('high_band', models.FloatField(default=0.5)),
                ('event_from', models.CharField(choices=[('annotations', 'annotations'), ('stim', 'stim')], default='Annotations', max_length=12)),
                ('on_missing', models.CharField(choices=[('Warn', 'warn'), ('Ignore', 'Ignore'), ('Raise', 'Raise')], default='Warn', max_length=12)),
                ('Stim_Chan', models.CharField(blank=True, max_length=100)),
                ('EEG_Chan', models.CharField(blank=True, max_length=200)),
                ('EOG_Chan', models.CharField(default="'EOG:ch01', 'EOG:ch02', 'EOG:ch03'", max_length=200)),
                ('exclude', models.CharField(default='bads', max_length=20)),
                ('projection', models.BooleanField(default=True)),
                ('baseline', models.CharField(default='None', max_length=20)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('output_shape', models.CharField(default='(1000,3,250)', max_length=50)),
                ('results_json', models.TextField(blank=True)),
                ('trained_model', models.FileField(blank=True, upload_to='')),
                ('private', models.BooleanField(default=False)),
                ('job_id', models.CharField(blank=True, max_length=33)),
                ('ai_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mindnet.aimodel')),
                ('crossvalidation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mindnet.crossvalidation')),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mindnet.dataset')),
                ('preprocess', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mindnet.preprocess')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_pipejob', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
