# Generated by Django 4.2.6 on 2024-01-15 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindnet', '0007_metric'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipejob',
            old_name='ai_model',
            new_name='aimodel',
        ),
    ]
