# Generated by Django 4.2.6 on 2024-01-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindnet', '0008_rename_ai_model_pipejob_aimodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipejob',
            old_name='EEG_Chan',
            new_name='eeg_channels',
        ),
        migrations.RemoveField(
            model_name='pipejob',
            name='EOG_Chan',
        ),
        migrations.RemoveField(
            model_name='pipejob',
            name='montage',
        ),
        migrations.AddField(
            model_name='pipejob',
            name='eog_channels',
            field=models.CharField(default="'EOG:ch01','EOG:ch02','EOG:ch03'", max_length=200),
        ),
        migrations.AlterField(
            model_name='pipejob',
            name='event_from',
            field=models.CharField(choices=[('annotations', 'anntions'), ('stim', 'stim')], default='Annotations', max_length=12),
        ),
        migrations.AlterField(
            model_name='pipejob',
            name='filter',
            field=models.CharField(choices=[(None, 'None'), ('Bandpass', 'Bandpass')], default='Bandpass', max_length=20),
        ),
        migrations.AlterField(
            model_name='pipejob',
            name='montage_type',
            field=models.CharField(choices=[(None, 'None'), ('standard_1005', 'standard_1005'), ('standard_1020', 'standard_1020')], default='None', max_length=20),
        ),
    ]
