# Generated by Django 4.2.6 on 2024-01-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindnet', '0010_alter_pipejob_evaluation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipejob',
            name='event_from',
            field=models.CharField(choices=[('A', 'Annotations'), ('SC', 'Stim Channel')], default='Annotations', max_length=2),
        ),
    ]
