# Generated by Django 4.2.6 on 2024-01-16 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mindnet', '0015_rename_results_json_pipejob_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipejob',
            name='metric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mindnet.metric'),
        ),
    ]
