# Generated by Django 4.2.6 on 2024-01-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindnet', '0016_pipejob_metric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipejob',
            name='montage_type',
            field=models.CharField(blank=True, choices=[(None, 'None'), ('standard_1005', 'standard_1005'), ('standard_1020', 'standard_1020')], default='None', max_length=20),
        ),
    ]
