# Generated by Django 4.2.6 on 2024-01-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindnet', '0020_alter_dataset_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipejob',
            name='montage_type',
            field=models.CharField(choices=[('None', 'None'), ('standard_1005', 'standard_1005'), ('standard_1020', 'standard_1020')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='pipejob',
            name='on_missing',
            field=models.CharField(choices=[('warn', 'warn'), ('ignore', 'Ignore'), ('raise', 'Raise')], default='warn', max_length=12),
        ),
    ]
