# Generated by Django 4.2.6 on 2024-01-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindnet', '0021_alter_pipejob_montage_type_alter_pipejob_on_missing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipejob',
            name='event_id',
            field=models.CharField(default='7,8', max_length=30),
        ),
        migrations.AlterField(
            model_name='pipejob',
            name='trained_model',
            field=models.FileField(blank=True, upload_to='models_trained'),
        ),
    ]
