# Generated by Django 4.2.6 on 2024-01-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindnet', '0025_alter_dataset_extracted_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='granted',
            field=models.BooleanField(default=False),
        ),
    ]
