# Generated by Django 4.2.6 on 2024-01-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindnet', '0027_remove_scaler_scaler_code_scaler_granted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scaler',
            name='scaler',
            field=models.FileField(blank=True, null=True, upload_to='Scalers/'),
        ),
    ]
