# Generated by Django 4.2.6 on 2024-01-21 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindnet', '0028_alter_scaler_scaler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scaler',
            name='scaler',
        ),
    ]
