# Generated by Django 4.2.6 on 2024-01-21 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindnet', '0029_remove_scaler_scaler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scaler',
            name='granted',
        ),
    ]
