# Generated by Django 4.2.6 on 2024-01-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindnet', '0030_remove_scaler_granted'),
    ]

    operations = [
        migrations.AddField(
            model_name='scaler',
            name='granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scaler',
            name='scaler',
            field=models.FileField(blank=True, null=True, upload_to='Scalers/'),
        ),
    ]
