# Generated by Django 4.2.6 on 2024-01-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindnet', '0031_scaler_granted_scaler_scaler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='metric_code',
        ),
        migrations.AddField(
            model_name='metric',
            name='granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metric',
            name='metric',
            field=models.FileField(blank=True, null=True, upload_to='Metrics/'),
        ),
    ]
