# Generated by Django 4.2.6 on 2024-02-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindnet', '0032_remove_metric_metric_code_metric_granted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='related_paper',
            field=models.ManyToManyField(blank=True, null=True, to='mindnet.paper'),
        ),
    ]
