# Generated by Django 4.2.6 on 2024-02-11 17:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mindnet', '0034_alter_dataset_related_paper'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crossvalidation',
            new_name='ValidationTechnique',
        ),
        migrations.RenameField(
            model_name='pipejob',
            old_name='crossvalidation',
            new_name='validationtechnique',
        ),
    ]
