# Generated by Django 4.2.6 on 2024-02-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindnet', '0036_pipejob_epoch_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipejob',
            name='duration',
            field=models.FloatField(default=4.0),
        ),
        migrations.AddField(
            model_name='pipejob',
            name='overlap',
            field=models.FloatField(default=1.0),
        ),
    ]
