# Generated by Django 4.2.6 on 2024-02-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindnet', '0037_pipejob_duration_pipejob_overlap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipejob',
            name='epoch_from',
            field=models.CharField(choices=[('E', 'Events'), ('F', 'Fixed Lenght')], default='E', max_length=2),
        ),
    ]
