# Generated by Django 4.2.6 on 2024-02-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindnet', '0040_alter_pipejob_evaluation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipejob',
            name='job_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
