# Generated by Django 4.2.6 on 2024-02-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindnet', '0041_alter_pipejob_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipejob',
            name='epoch_from',
            field=models.CharField(choices=[('Events', 'Events'), ('Fixed Lenght', 'Fixed Lenght')], default='Events', max_length=15),
        ),
        migrations.AlterField(
            model_name='pipejob',
            name='event_from',
            field=models.CharField(choices=[('Annotations', 'Annotations'), ('Stim Channel', 'Stim Channel')], default='Annotations', max_length=15),
        ),
    ]
